#spring:
#  datasource:
#    url: jdbc:mysql://3.1.57.63:6603/av_yf_ag?characterEncoding=UTF-8&autoReconnect=true
#    #   url: jdbc:mysql:// AFBCS-YF-DB-M:6603/av_yf_ag?characterEncoding=UTF-8&autoReconnect=true
#    username: csavdep
#    password: AVDB#@!~)xIsKHa&92IxK01*
#    hikari:
#      auto-commit: false
#      maximum-pool-size: 10
#      minimum-idle: 5
#  cloud:
#    consul:
#      enabled: false
#afb:
#  url: https://cs-awsyfag.gm10099.com/afbapiyflivesw/app/api.do
#  hashCode: quickLoginTest_ce35e773-ddd1-42b2-99
#server:
#  port: 8800

#com:
#  alliance:
#    live-game:
#      fast-login:
#        api-para:
#          language: VN # 泰國測試線
#          url: https://cs-awsyfag.gm10099.com/afbapiyflivesw/app/api.do
#          hashCode: 'kgtestvnd03_993c9a19-b73e-4f7b-857c-'
#eureka:
#  client:
#    enabled: false